[theme]
base = "light"
primaryColor = "#34b3a0"        # Tu verde azulado (para botones y foco)
backgroundColor = "#ffffff"     # Fondo blanco puro (m√°ximo contraste)
secondaryBackgroundColor = "#f0f2f6" # Gris muy suave para el sidebar y burbujas de IA
textColor = "#153244"           # Tu azul oscuro (para el texto, se lee perfecto sobre blanco)
font = "sans serif"
